#!/usr/bin/env perl

use Mojolicious::Lite;
use DBI;

# Documentation browser under "/perldoc"
plugin 'PODRenderer';

app->secret('this is the secret pass phrase');

my $dbh = DBI->connect('dbi:Pg:dbname=zipcodes','trayton','', {AutoCommit => 1})
    or die "Could not connect to database.";

# add helper method for interacting with the db
helper db => sub { $dbh };

# create helper method for selecting zip codes from db
helper selectzips => sub {
    my $self = shift;
    my ($zipcode, $radius, $units) = @_;
#    my @zipsinradius = 
#    my $listofzips = join( ',', map { '?' } @zipsinradius );
    my $sth = eval { $self->db->prepare("select zip, lat, lon,
            ?::real as radius,
            ?::varchar as units
            from ziplatlon where zip = ?") }
        || return undef;
    $sth->execute($radius, $units, $zipcode);
    return $sth->fetchall_arrayref;
};

# helper method to calculate distances
helper distancecalc => sub {
    my $self = shift;
    my ($zipcode) = @_;
};

any '/' => sub {
    my $self    = shift;
    my $zipcode = $self->param('zipcode');
    my $radius  = $self->param('radius');
    my $units   = $self->param('units');
    my $rows    = $self->selectzips($zipcode, $radius, $units);
    $self->stash( rows => $rows );
    $self->render('index');
};

app->start;

__DATA__

@@ index.html.ep

<!DOCTYPE html>
<html>
  <head>
    <title>Zip Code Radius</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
      html { height: 90%; width: 95% }
      body { height: 90%; width: 95%; margin-left: auto; margin-right: auto; padding: 0 }
      #map-canvas { height: 90%; width: 100% }
    </style>
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAJJp6S9OpfZxra51nqDF2pP5piTgFM1tc&sensor=false">
    </script>
    <script type="text/javascript">
      function initialize() {
        var mapOptions = {
          center: new google.maps.LatLng(<%= $rows->[0][1]%>, <%= $rows->[0][2] %>),
          zoom: 4,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"),
          mapOptions);
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
  </head>
  <body>
  <table>
    <div id="map-canvas"/>
    </table>
<br>
<center>    <table>
<form action="<%=url_for('')->to_abs%>" method="post">
    Zip Code:   <input type="text" name="zipcode">
    Radius:     <input type="text" name="radius">
    Units:      <input type="radio" name="units" value="km"> km
                <input type="radio" name="units" value="miles"> miles
    <br>
                <input type="submit" value="Calculate">
</form>
<br>
<br>
<table border="1">
    <tr>
        <th>Zip Code</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Radius</th>
        <th>Units</th>
    </tr>
    % for my $row (@$rows) {
    <tr>
        % for my $text (@$row) {
            <td><%= $text %></td>
        % }
    % }
</table>
</table>
</center>
</body>
</html>

